@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(user, "User")
Container(loadBalancer, "Load Balancer", "Nginx", "Uses round robin")
Container(followsQueue, "Follows Queue", "Apache Kafka", "Stores follow events [followed, unfollowed]", $tags="messageQueue")

System_Boundary(followsSystem, "Follows system") {
    Container(followsService, "Follows Service", "Go", "Handles following, unfollowing mechanism", $tags="webApp")
    ContainerDb(followsDatabase, "Follows Database", "PostgreSQL", "Stores follows information",  $tags="db")
}

System_Boundary(externalSystem, "External systems") {
    Container(postsSystem, "Posts System", "Software system")
}

Rel(user, loadBalancer, "CRUD operations with follows", "REST")
Rel(loadBalancer, followsService, "CRUD operations with follows", "REST")
Rel(followsQueue, postsSystem, "Consumes follow events")
Rel(followsService, followsQueue, "Produces follow events")
Rel(followsService, followsDatabase, "Stores follows information")
@enduml